### ISSUE TITLE
Command 'Include What You use (current file)' resulted in an error

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [helly25/vscode-iwyu#2]
command 'iwyu.run.one' not found

I get above error when trying to invoke IWYU from the command palette in vscode. I can run `iwyu_tool.py --help` normally in the terminal so path shouldn't be a problem I guess.

**Comment by helly25** [comment]
That sounds like an installation problem to me. Could you check whether uninstalling the extension, restarting the IDE and reinstalling the extension helps? If it does not help we need to check your logs. When you go to "Output" you should be able to select "IWWYU".

**Comment by mgarbacz** [comment]
I'm encountering the same error. 

Output for IWYU only shows:
```
[info] Extension activated
```

However, output for the Extension Host shows:
```
[info] ExtensionService#_doActivateExtension helly25.helly25iwyu, startup: false, activationEvent: 'onLanguage:cpp'
[error] Activating extension helly25.helly25iwyu failed due to an error:
[error] Error: ENOENT: no such file or directory, stat '/my/real/workspace/folder/path/compile_commands.json'
```

I used a false path in that log for privacy, but it was looking directly in the workspace folder, as is the default. I have my `compile_commands.json` in `${workspaceFolder}/build/`.

I have `"iwyu.compile_commands": "${workspaceFolder}/build/compile_commands.json"` set in my settings.json, which was put there when I used the settings GUI to change that setting for the extension. I've tried restarting VS Code, reinstalling the extension, and various combinations of the two.

I took a glance at the source code here, and I don't believe it is ever checking that config option and thereby simply defaulting to the default. I could be misunderstanding it or missing something.

**Comment by mgarbacz** [comment]
For giggles, I copied my `compile_commands.json` into the root workspace folder and that does work. My path setting is still set to my correct build pathing:

![Screen Shot 2023-10-20 at 21 04 22](https://github.com/helly25/vscode-iwyu/assets/1039832/ae624b43-b761-4e20-9b2c-58e38908b8cc)

**Comment by helly25** [comment]
Thanks for the detailed info @mgarbacz. I could reproduce the issue and fix it. The extension will now show an error both in the log and in the UI. The new version 0.0.15 can be downloaded. Please let me know if that fixes the issue.

**Comment by helly25** [comment]
Since I could reproduce the original report and it is fixed. I will close the bug. If there is still an issue, please reopen or file a new bug.
