### ISSUE TITLE
Extension can't be used in with VSCode Workspaces

### ISSUE THREAD

**Issue by samopolacek** [helly25/vscode-iwyu#3]
The path to compile_commands,json, in case of a VSCode Workspace, is usually relative to ${fileWorkspaceFoler}, which is not supported by the extension.

**Comment by helly25** [comment]
You need to set: `iwyu.compile_commands` in your VSCode user or workspace settings (see https://github.com/helly25/vscode-iwyu/?tab=readme-ov-file#extension-settings).  This was unfortunately documented wrong in the README.

You can set it like this:

```json
{
    "iwyu.compile_commands": "${workspaceFolder}/compile_commands.json"
}
```

Note that `${workspaceFolder}/compile_commands.json` is actually the default.

**Comment by helly25** [comment]
The reason you would still want `${fileWorkspaceFoler}` over `${workspaceFoler}` is that you are in a very rare case of multi-root-workspace. In all other case you can use the default of `${workspaceFoler}`. If you are using CMake or other build-tool that places `compile_commands.json` under build, then for now you can just change the default in your settings as described in my earlier response.

Let me know if you are in a multi-root-workspace case.

**Comment by helly25** [comment]
This could maybe work. A rudimentary attempt is implemented in the current state of https://github.com/helly25/vscode-iwyu/pull/10. Could you check if that works for you?

**Comment by helly25** [comment]
I extracted just the multi-root-workspace work into https://github.com/helly25/vscode-iwyu/pull/12.

**Comment by helly25** [comment]
@samopolacek: The rudimentary multi-root-workspace support was just published as 0.1.16. Let me know how that works for you. If you find it lacking please reopen the issue.

**Comment by samopolacek** [comment]
@helly25 Yes, I am in a multi root workspace, hence I used fileWorkspaceFolder. I noticed that the extension started to work and was wondering why - it was #12 . Thank you!

**Comment by helly25** [comment]
Great to hear. I still need to find more time to debug such cases though before calling it an actual feature.
