### ISSUE TITLE
Command has no effect

### ISSUE THREAD

**Issue by EloWork** [helly25/vscode-iwyu#8]
When executing the IWYU command from the command palette, there is nothing happening. Even with debug level set to Trace, there is no output whatsoever, also no error squiggles or any indication of the plugin working.

**Comment by Gpinchon** [comment]
I'm having the exact same issue, is this extension still alive ?

**Comment by helly25** [comment]
Hi, when the extension is installed, then you will be able to see that in the extension list. It must show up as activated. If it is activated and you select a C/C++ source file editor, then the extension will start up. If you go to the output pane you can select "IWYU". In the just uploaded version 0.0.16 you should see something like:

```
2024-07-08 18:47:19.332 [info] Extension activated
2024-07-08 18:47:19.332 [debug] Using compileCommandsJson = '/Users/helly25/Documents/helly25/mbo/compile_commands.json'.
2024-07-08 18:47:19.332 [debug] Parsing: `/Users/helly25/Documents/helly25/mbo/compile_commands.json`
```

If that does not show anything-or "IWYU" cannot be selected, then please check your log level. Go to the Command Selection (Command+Shift+P) and select "Developer: Select Log Level...". In the top section of the menu you can select the default log level. In the lower part you can select a specific extension and then the log level for that extension. Make sure that IWYU is set to at least INFO.

**Comment by EloWork** [comment]
At least I have log output now.
```
Command failed: include-what-you-use -Xiwyu --max_line_length=80  -Xiwyu --transitive_includes_only - -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_EXPLICIT_BZERO=1 -DHAVE_LIBNUMA=1 -DHAVE_NUMA_ALLOCATE_NODEMASK=1 -DHAVE_PAM_DEVEL=1 -DHAVE_BPF_DEVEL=1 -DHAVE_MUNGE_DEVEL=1 -DHAVE_SLURM_SPANK_H=1 -DHAVE_SPANK=1 -DHAVE_DECL_S_TASK_ARGV=0 -I. -I../../include -DNDEBUG -I../../bin/daemon -DPLUGINDIR="/usr/local/plugins" -O3 -Wall -Wextra -Wno-unused-parameter -fstack-protector-all -fno-strict-aliasing -g -c -fPIC -DPIC -o .libs/dynIP_la-dynIP.o dynIP.c 2>&1
In file included from dynIP.c:10:
In file included from /usr/include/arpa/inet.h:22:
In file included from /usr/include/netinet/in.h:23:
In file included from /usr/include/sys/socket.h:26:
/usr/include/bits/types/struct_iovec.h:23:10: fatal error: 'stddef.h' file not found
   23 | #include <stddef.h>
      |          ^~~~~~~~~~
```

**Comment by EloWork** [comment]
The location is indeed `/usr/include/linux/stddef.h`. I was hoping the `compile_commands.json` contains 100% information needed for IWYU. Especially since iwyu works from command line, so the extension behaves a tiny bit different here. The compiler is gcc (8.5). I included all built-in paths listed in `echo | gcc -xc -E -v -`. The extension works now for this file (and I think all files where the command line works too). Thanks for the help.

**Comment by CsatiZoltan** [comment]
@EloWork , @helly25 I face the same problem, but with C++ headers:
```
fatal error: 'iostream' file not found
   32 | #include <iostream>
      |          ^~~~~~~~~~
```
So I followed your advice and added `-I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11/bits` to `iwyu.iwyu.additional_params`. For some reason IWYU still cannot see the *bits/* subdirectory:
```
/usr/include/c++/11/iostream:38:10: fatal error: 'bits/c++config.h' file not found
   38 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
```

Do you have any idea how to solve this problem?

I have two GCC compilers installed, one via the Ubuntu package manager (version 11.4.0), the other one via conda (12.3.0):
```bash
$ locate c++config.h
/home/zozo/mambaforge/pkgs/libstdcxx-devel_linux-64-12.3.0-h0223996_107/x86_64-conda-linux-gnu/include/c++/12.3.0/x86_64-conda-linux-gnu/bits/c++config.h
/usr/include/x86_64-linux-gnu/c++/11/bits/c++config.h
```
I tried with both paths, but the same issue: bits/c++config.h is not found.

**Comment by EloWork** [comment]
Have you tried `-I/usr/include/x86_64-linux-gnu/c++/11/`? Because `bits` is already in tbe include

**Comment by CsatiZoltan** [comment]
You are right, but then again: `stdarg.h` is missing. Adding more include paths, now I get
```
/usr/include/wchar.h:272:53: error: unknown type name 'size_t'; did you mean 'std::size_t'?
```
